### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by iiewad** [iofu728/spider#33]
➜  spider git:(master) python3 ctrip/hotelDetail.py                                                                                                                                                                                  [178/228]
{'magicid': 'xJhxAVzmtKzWRwWv9qmaIgqvzK66z38v9JCEpID+q9DBaLSQv4yIN4/TI76Mhhde'}
 You're bot
 Num of a6[h][i] 0
 Num 0f end 1
Traceback (most recent call last):
  File "ctrip/hotelDetail.py", line 509, in <module>
    ch.parse_detail()
  File "ctrip/hotelDetail.py", line 386, in parse_detail
    text = self.get_hotel_detail(hotel_id)
  File "ctrip/hotelDetail.py", line 368, in get_hotel_detail
    'eleven': self.generate_eleven_v2(hotel_id),
  File "ctrip/hotelDetail.py", line 243, in generate_eleven_v2
    eleven = js2py.eval_js(oj + ';aabb()')
  File "/usr/local/lib/python3.7/site-packages/js2py/evaljs.py", line 115, in eval_js
    return e.eval(js)
  File "/usr/local/lib/python3.7/site-packages/js2py/evaljs.py", line 204, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/usr/local/lib/python3.7/site-packages/js2py/evaljs.py", line 199, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "/usr/local/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python3.7/site-packages/js2py/base.py", line 1463, in call
    return Js(self.code(*args))
  File "/usr/local/lib/python3.7/site-packages/js2py/host/jseval.py", line 17, in Eval
    py_code = translate_js(code.to_string().value, '')
  File "/usr/local/lib/python3.7/site-packages/js2py/translators/translator.py", line 65, in translate_js
    parsed = parser.parse(js)  # js to esprima syntax tree
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 3008, in parse
    program = self.parseProgram()
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2974, in parseProgram
    body = self.parseScriptBody()
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2963, in parseScriptBody
    statement = self.parseStatementListItem()
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2105, in parseStatementListItem
    return self.parseFunctionDeclaration(Node())
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2878, in parseFunctionDeclaration
    body = self.parseFunctionSourceElements()
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2765, in parseFunctionSourceElements
    body.append(self.parseStatementListItem())
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2110, in parseStatementListItem
    return self.parseStatement()
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2705, in parseStatement
    expr = self.parseExpression()
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 2076, in parseExpression
    expr = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "/usr/local/lib/python3.7/site-packages/pyjsparser/parser.py", line 1161, in isolateCoverGrammar
    result = parser()

**Comment by iofu728** [comment]
It looks like the js obfuscated code has changed, and originally code not applicable.
I'll see it when I free.

**Comment by iiewad** [comment]
> It looks like the js obfuscated code has changed, and originally code not applicable.
> I'll see it when I free.

thx.
